# .NET Desktop
 task: FortifyOnDemandStatic@3
  inputs:
    FortifyProjects: 'https://github.com/WebGoat/WebGoat.git'
    BSIToken: 'eyJ0ZW5hbnRJZCI6MTM5MiwidGVuYW50Q29kZSI6InBsdXNfZGVtbyIsInJlbGVhc2VJZCI6MjE0Mzg3LCJwYXlsb2FkVHlwZSI6IkFOQUxZU0lTX1BBWUxPQUQiLCJhc3Nlc3NtZW50VHlwZUlkIjoyNzQsInRlY2hub2xvZ3lUeXBlIjoiLk5FVCIsInRlY2hub2xvZ3lUeXBlSWQiOjEsInRlY2hub2xvZ3lWZXJzaW9uIjoiNC42IiwidGVjaG5vbG9neVZlcnNpb25JZCI6MTUsImF1ZGl0UHJlZmVyZW5jZSI6IkF1dG9tYXRlZCIsImF1ZGl0UHJlZmVyZW5jZUlkIjoyLCJpbmNsdWRlVGhpcmRQYXJ0eSI6ZmFsc2UsImluY2x1ZGVPcGVuU291cmNlQW5hbHlzaXMiOnRydWUsInBvcnRhbFVyaSI6Imh0dHBzOi8vYW1zLmZvcnRpZnkuY29tIiwiYXBpVXJpIjoiaHR0cHM6Ly9hcGkuYW1zLmZvcnRpZnkuY29tIiwic2NhblByZWZlcmVuY2UiOiJTdGFuZGFyZCIsInNjYW5QcmVmZXJlbmNlSWQiOjF9'
    APIAuthenticationType: '1'
    APIKey: '74fe9f3e-1680-4a68-8cb6-3380b7e762b1'
    APISecret: 'djBITDBkaE1ibUVPbUsuM1laY0FzUDVlXyVrMGhj0'
    EntitlementPreference: '1'
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: FortifyOnDemandStatic@3
  inputs:
    FortifyProjects: 'https://github.com/uat-carena/FrAbel.git'
    BSIToken: 'eyJ0ZW5hbnRJZCI6MTM5MiwidGVuYW50Q29kZSI6InBsdXNfZGVtbyIsInJlbGVhc2VJZCI6MjE0Mzg3LCJwYXlsb2FkVHlwZSI6IkFOQUxZU0lTX1BBWUxPQUQiLCJhc3Nlc3NtZW50VHlwZUlkIjoyNzQsInRlY2hub2xvZ3lUeXBlIjoiLk5FVCIsInRlY2hub2xvZ3lUeXBlSWQiOjEsInRlY2hub2xvZ3lWZXJzaW9uIjoiNC41IiwidGVjaG5vbG9neVZlcnNpb25JZCI6MTEsImF1ZGl0UHJlZmVyZW5jZSI6IkF1dG9tYXRlZCIsImF1ZGl0UHJlZmVyZW5jZUlkIjoyLCJpbmNsdWRlVGhpcmRQYXJ0eSI6ZmFsc2UsImluY2x1ZGVPcGVuU291cmNlQW5hbHlzaXMiOnRydWUsInBvcnRhbFVyaSI6Imh0dHBzOi8vYW1zLmZvcnRpZnkuY29tIiwiYXBpVXJpIjoiaHR0cHM6Ly9hcGkuYW1zLmZvcnRpZnkuY29tIiwic2NhblByZWZlcmVuY2UiOiJTdGFuZGFyZCIsInNjYW5QcmVmZXJlbmNlSWQiOjF9'
    APIAuthenticationType: '1'
    APIKey: '74fe9f3e-1680-4a68-8cb6-3380b7e762b1'
    APISecret: 'djBITDBkaE1ibUVPbUsuM1laY0FzUDVlXyVrMGhj0'
    EntitlementPreference: '1'